<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WRBh6e4' shared service.

return $this->privates['.service_locator.WRBh6e4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'emm' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'helpers' => ['privates', 'App\\Service\\Ayuda', 'getAyudaService.php', true],
], [
    'emm' => '?',
    'helpers' => 'App\\Service\\Ayuda',
]);
