<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qgsBlwd' shared service.

return $this->privates['.service_locator.qgsBlwd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PersonajesController::detallespersonajes' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesController::newpersonaje' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesController::seleccionpersonaje' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesController::tap' => ['privates', '.service_locator.WRBh6e4', 'get_ServiceLocator_WRBh6e4Service.php', true],
    'App\\Controller\\PersonajesPlantillasController::crearclase' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesPlantillasController::getplantilla' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesPlantillasController::personajeplantillas' => ['privates', '.service_locator.EEzFW8.', 'get_ServiceLocator_EEzFW8_Service.php', true],
    'App\\Controller\\UsuariosController::editar' => ['privates', '.service_locator.lpLc0q0', 'get_ServiceLocator_LpLc0q0Service.php', true],
    'App\\Controller\\UsuariosController::getdetalles' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\UsuariosController::login' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\UsuariosController::registro' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\UsuariosController::uploadSingleImage' => ['privates', '.service_locator.lpLc0q0', 'get_ServiceLocator_LpLc0q0Service.php', true],
    'App\\Controller\\PersonajesController:detallespersonajes' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesController:newpersonaje' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesController:seleccionpersonaje' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesController:tap' => ['privates', '.service_locator.WRBh6e4', 'get_ServiceLocator_WRBh6e4Service.php', true],
    'App\\Controller\\PersonajesPlantillasController:crearclase' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesPlantillasController:getplantilla' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\PersonajesPlantillasController:personajeplantillas' => ['privates', '.service_locator.EEzFW8.', 'get_ServiceLocator_EEzFW8_Service.php', true],
    'App\\Controller\\UsuariosController:editar' => ['privates', '.service_locator.lpLc0q0', 'get_ServiceLocator_LpLc0q0Service.php', true],
    'App\\Controller\\UsuariosController:getdetalles' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\UsuariosController:login' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\UsuariosController:registro' => ['privates', '.service_locator.bp.LIhG', 'get_ServiceLocator_Bp_LIhGService.php', true],
    'App\\Controller\\UsuariosController:uploadSingleImage' => ['privates', '.service_locator.lpLc0q0', 'get_ServiceLocator_LpLc0q0Service.php', true],
], [
    'App\\Controller\\PersonajesController::detallespersonajes' => '?',
    'App\\Controller\\PersonajesController::newpersonaje' => '?',
    'App\\Controller\\PersonajesController::seleccionpersonaje' => '?',
    'App\\Controller\\PersonajesController::tap' => '?',
    'App\\Controller\\PersonajesPlantillasController::crearclase' => '?',
    'App\\Controller\\PersonajesPlantillasController::getplantilla' => '?',
    'App\\Controller\\PersonajesPlantillasController::personajeplantillas' => '?',
    'App\\Controller\\UsuariosController::editar' => '?',
    'App\\Controller\\UsuariosController::getdetalles' => '?',
    'App\\Controller\\UsuariosController::login' => '?',
    'App\\Controller\\UsuariosController::registro' => '?',
    'App\\Controller\\UsuariosController::uploadSingleImage' => '?',
    'App\\Controller\\PersonajesController:detallespersonajes' => '?',
    'App\\Controller\\PersonajesController:newpersonaje' => '?',
    'App\\Controller\\PersonajesController:seleccionpersonaje' => '?',
    'App\\Controller\\PersonajesController:tap' => '?',
    'App\\Controller\\PersonajesPlantillasController:crearclase' => '?',
    'App\\Controller\\PersonajesPlantillasController:getplantilla' => '?',
    'App\\Controller\\PersonajesPlantillasController:personajeplantillas' => '?',
    'App\\Controller\\UsuariosController:editar' => '?',
    'App\\Controller\\UsuariosController:getdetalles' => '?',
    'App\\Controller\\UsuariosController:login' => '?',
    'App\\Controller\\UsuariosController:registro' => '?',
    'App\\Controller\\UsuariosController:uploadSingleImage' => '?',
]);
