App\Entity\Personajes:
    type: entity
    repositoryClass: App\Repository\PersonajesRepository
    table: personajes
    indexes:
        fk_loginpersonaje:
            columns:
                - login
    id:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        login:
            targetEntity: Usuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                login:
                    referencedColumnName: login
            orphanRemoval: false
    lifecycleCallbacks: {  }
