App\Entity\Usuarios:
    type: entity
    repositoryClass: App\Repository\UsuariosRepository
    table: usuarios
    id:
        login:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        password:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
