<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQitO0wE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQitO0wE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQitO0wE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQitO0wE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQitO0wE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QitO0wE',
    'container.build_id' => '28fca772',
    'container.build_time' => 1585298540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQitO0wE');
